### PR TITLE
Mobile js/menu

### PR DESCRIPTION
**Pull request by enmanuelbayen**
Added the following features: 

 - Full-menu section on the mobile version
 - JS event when clicking on hamburger menu/mobile-version
 - New linters for JS 
 - Html container for full-menu on header section
 - Create a new menu.css file
 - Linters fix

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that's not having the exact required linters configuration. Kindly ensure that the .github/workflows/linters.yml file has the same content as in the [Microverse linters configuration](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) for html/css/js projects.

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by enmanuelbayen** [comment]
Added and Fixed linters error for JS

**Review by rloterh — COMMENTED** [review]
Hi Enmanuel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented:
- Ensure that provided placeholder texts/ guide instructions are removed or replaced with appropriate contents applicable under each section of your ReadMe.

**Examples are underlined below:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by didierganthier — COMMENTED** [review]
Hi @enmanuelbayen ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.



## Invalid Code Review Request 🚫

- You have submitted the PR for the mobile menu activity in the activity of the details popup window. ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

**Comment by enmanuelbayen** [comment]
Update on the readme file

- Remove guidelines

**Review by didierganthier — APPROVED** [review]
Hi Team,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀



## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 
- Mobile Menu working ✔️ 

## Optional Suggestions 💡
- N/A

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

**Pull request merged**
